apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-simple
spec:
  rules:
    - host: http-simple.api.localhost
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: http-simple
                port:
                  name: http
