namespace: http-simple

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - namespace.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: http-simple-env
    envs:
      - .env
  - name: http-simple-certificate
    files:
      - assets/certificate.pem

secretGenerator:
  - name: http-simple-key
    files:
      - assets/key.pem
